#!/usr/bin/env ruby

require 'yaml'

puts "enter the following in your
developer console to automate
infinite scroll clicks. Wait until it reaches the end.\n\n"

puts <<-JS
var interval = window.setInterval(function(){
    $('html, body').scrollTop( $(document).height() - $(window).height() );
}, 250)
JS

puts "\n\nwhen it is done, enter the following:\n\n "

puts <<-JS
window.clearInterval(interval)
JS

puts "\n\npress enter when done\n\n"
input = gets.chomp

puts "enter the following Javascript:\n\n"

puts <<-JS
  var $body = $("body");
  $(".header-info").each(
    function(idx, elem) {
      var $el = $(elem);
      var name = $el.find(".startup-link").text();
      var desc = $el.find(".tagline").text();
      $body.prepend("name: " + name + ",<br>" + "desc: " + desc + "<br><br>") 
    }
  );
JS

puts "\n\npress enter when done\n\n"
input = gets.chomp

puts "copy the text at the top of the screen to your yaml file and format is appropriately."